export const HEALTH_GOALS = [
  { id: 'pcos', label: 'PCOS Support', icon: '🌸', description: 'Balance hormones & reduce inflammation', color: '#F2C4CE' },
  { id: 'fertility', label: 'Fertility & Conception', icon: '🌱', description: 'Nourish your body for conception', color: '#C8E6C4' },
  { id: 'hormones', label: 'Hormone Balance', icon: '⚖️', description: 'Regulate mood, energy & cycle', color: '#F5E6A3' },
  { id: 'energy', label: 'Low Energy & Fatigue', icon: '✨', description: 'Fuel your body from the inside out', color: '#FFD9B3' },
  { id: 'period', label: 'Period Regulation', icon: '🔴', description: 'Support a healthy, regular cycle', color: '#F4C4C4' },
  { id: 'gut', label: 'Gut Health', icon: '🌿', description: 'Heal your gut, heal your health', color: '#C4DEB8' },
  { id: 'thyroid', label: 'Thyroid Support', icon: '🦋', description: 'Nourish your thyroid naturally', color: '#B8D4E8' },
  { id: 'menopause', label: 'Menopause', icon: '🌙', description: 'Ease the transition with nutrition', color: '#D4B8E8' },
  { id: 'postpartum', label: 'Postpartum Recovery', icon: '💛', description: 'Replenish & restore after birth', color: '#F5E6A3' },
  { id: 'endometriosis', label: 'Endometriosis', icon: '🩷', description: 'Anti-inflammatory, pain-reducing foods', color: '#F2C4CE' },
]

export const HEALTH_LABEL_MAP = {
  pcos: { label: 'PCOS', color: '#F2C4CE', text: '#8B3A52' },
  fertility: { label: 'Fertility', color: '#C8E6C4', text: '#2E6B3E' },
  hormones: { label: 'Hormones', color: '#F5E6A3', text: '#7A6000' },
  energy: { label: 'Energy', color: '#FFD9B3', text: '#8B4A00' },
  period: { label: 'Period Health', color: '#F4C4C4', text: '#8B2020' },
  gut: { label: 'Gut Health', color: '#C4DEB8', text: '#2E5E1E' },
  thyroid: { label: 'Thyroid', color: '#B8D4E8', text: '#1E4E6E' },
  menopause: { label: 'Menopause', color: '#D4B8E8', text: '#4A2E6E' },
  postpartum: { label: 'Postpartum', color: '#F5E6A3', text: '#6E5000' },
  endometriosis: { label: 'Endo', color: '#F2C4CE', text: '#6E1E3A' },
  'high-protein': { label: 'High Protein', color: '#D4C4B0', text: '#4A3020' },
  'anti-inflammatory': { label: 'Anti-Inflammatory', color: '#C4DEB8', text: '#2E5E1E' },
  'gut-friendly': { label: 'Gut-Friendly', color: '#C8E6C4', text: '#2E6B3E' },
}

export const dieticians = [
  {
    id: 1,
    name: 'Elin Warn',
    credentials: 'RD, MSc',
    specialty: 'Gut Health & High-Protein Nutrition',
    bio: 'Registered Dietitian passionate about making gut-friendly, high-protein food that actually tastes incredible. Based in Stockholm.',
    initials: 'EW',
    avatarColor: '#C4A882',
    followers: 24700,
    following: 312,
    tags: ['gut', 'high-protein', 'pcos'],
    recipeIds: [1, 2, 3],
  },
  {
    id: 2,
    name: 'Dr. Maya Chen',
    credentials: 'RD, PhD',
    specialty: 'PCOS & Hormonal Health',
    bio: 'PhD in Nutritional Science. I help women with PCOS reclaim their health through evidence-based nutrition. Researcher & clinician.',
    initials: 'MC',
    avatarColor: '#8FA888',
    followers: 18300,
    following: 204,
    tags: ['pcos', 'hormones', 'fertility'],
    recipeIds: [4, 5, 6],
  },
  {
    id: 3,
    name: 'Sophie Laurent',
    credentials: 'RD, IBCLC',
    specialty: 'Fertility, Prenatal & Postpartum Nutrition',
    bio: 'Supporting women from preconception through postpartum. Lactation consultant & registered dietitian. Food is medicine.',
    initials: 'SL',
    avatarColor: '#D4A5A5',
    followers: 31200,
    following: 187,
    tags: ['fertility', 'postpartum', 'hormones'],
    recipeIds: [7, 8, 9],
  },
  {
    id: 4,
    name: 'Amara Osei',
    credentials: 'RD, CNS',
    specialty: 'Endometriosis & Anti-Inflammatory Eating',
    bio: 'Certified Nutrition Specialist focused on reducing inflammation through food. Living with endo myself — I get it.',
    initials: 'AO',
    avatarColor: '#B8A0C8',
    followers: 14900,
    following: 423,
    tags: ['endometriosis', 'anti-inflammatory', 'period'],
    recipeIds: [10, 11, 12],
  },
  {
    id: 5,
    name: 'Julia Reyes',
    credentials: 'RD, RN',
    specialty: 'Thyroid & Autoimmune Nutrition',
    bio: 'Registered Dietitian & Nurse. Hashimoto\'s warrior helping women navigate thyroid disease through targeted nutrition strategies.',
    initials: 'JR',
    avatarColor: '#A0B8D4',
    followers: 9600,
    following: 289,
    tags: ['thyroid', 'energy', 'gut'],
    recipeIds: [13, 14, 15],
  },
]

export const recipes = [
  {
    id: 1,
    title: 'High Protein, Gut-Friendly Bread',
    subtitle: 'Fluffy, nourishing & delicious',
    dieticianId: 1,
    healthLabels: ['gut', 'high-protein', 'pcos'],
    prepTime: '15 min',
    cookTime: '35 min',
    servings: 8,
    gradient: 'linear-gradient(145deg, #F5E6C8 0%, #DEB887 60%, #C8956C 100%)',
    emoji: '🍞',
    ingredients: [
      '8 egg whites',
      '2.5 dl cottage cheese',
      '10 dl bread flour',
      '25 g fresh yeast',
      '1 dl lukewarm water',
      '2 tbsp olive oil',
      '1.5 tsp salt',
      '1 tsp honey (optional)',
    ],
    instructions: [
      'Preheat oven to 200°C.',
      'Dissolve yeast in lukewarm water with honey.',
      'Mix egg whites, cottage cheese and olive oil together.',
      'Add flour and salt, knead into a smooth dough.',
      'Let rise for 1 hour.',
      'Shape into a loaf or place in a lined tin.',
      'Brush with egg white and sprinkle your favourite toppings.',
      'Bake for 30–35 minutes until golden. Save for later xx',
    ],
    note: 'Store in an airtight container for up to 4 days. Slice and freeze for easy mornings.',
  },
  {
    id: 2,
    title: 'Gut-Friendly Bagels',
    subtitle: 'Sugar-free & high protein',
    dieticianId: 1,
    healthLabels: ['gut-friendly', 'high-protein', 'energy'],
    prepTime: '10 min',
    cookTime: '30 min',
    servings: 4,
    gradient: 'linear-gradient(145deg, #F0D9C0 0%, #C8956C 60%, #A0724A 100%)',
    emoji: '🥯',
    ingredients: [
      '2 dl cottage cheese',
      '1 dl Greek yogurt',
      '4 dl all-purpose flour',
      '1.5 tsp baking powder',
      '1 tsp salt',
      '2 eggs (one for egg wash)',
      'Toppings: sesame seeds, poppy seeds, cheese or spices',
    ],
    instructions: [
      'Preheat oven to 190°C.',
      'Mix dry ingredients together.',
      'Add cottage cheese & Greek yogurt. Mix with a spoon or hands until a dough forms.',
      'Divide into 4 portions. Roll into a ball, poke a hole in the centre and gently form a bagel shape.',
      'Brush with egg yolk and add toppings.',
      'Bake for 25–30 minutes or until golden brown.',
      'Let cool before serving. Enjoy with cream cheese, scrambled eggs, salmon or avocado.',
    ],
    note: 'Great with cream cheese, smoked salmon, or avocado.',
  },
  {
    id: 3,
    title: 'Cinnamon, Cardamom & Vanilla Oatmeal',
    subtitle: 'Creamy spicy oatmeal — like a warm hug',
    dieticianId: 1,
    healthLabels: ['gut', 'energy', 'hormones'],
    prepTime: '5 min',
    cookTime: '20 min',
    servings: 2,
    gradient: 'linear-gradient(145deg, #E8D5B7 0%, #C4A882 60%, #A08060 100%)',
    emoji: '🥣',
    ingredients: [
      '1 dl gluten-free or regular oats',
      '½ dl gluten-free steel-cut oats',
      '½ dl mixed seeds',
      '2 tbsp cinnamon, 2 tbsp cardamom, 1 tbsp ginger powder',
      '2 tbsp vanilla powder',
      'Salt to taste',
      '2 dl oat milk (or other milk)',
    ],
    instructions: [
      'Blend the gluten-free oats, steel-cut oats and seeds together.',
      'Add the cinnamon, cardamom, ginger & vanilla powder to the oatmeal mix.',
      'Boil 6 dl of water in a pot.',
      'Add the oatmeal mix to the boiling water and cook on low heat for 10 minutes, stirring occasionally.',
      'Add oat milk and salt to taste, and let simmer for another 10 minutes.',
    ],
    note: 'Make extra oatmeal-mix to store and easily cook later. xx',
  },
  {
    id: 4,
    title: 'PCOS Berry Hormone Bowl',
    subtitle: 'Inositol-rich & anti-androgenic',
    dieticianId: 2,
    healthLabels: ['pcos', 'hormones', 'fertility'],
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 1,
    gradient: 'linear-gradient(145deg, #F5C8D5 0%, #E899B4 60%, #C86090 100%)',
    emoji: '🫐',
    ingredients: [
      '1 cup frozen mixed berries (blueberries, strawberries, raspberries)',
      '½ banana, frozen',
      '½ cup Greek yogurt',
      '1 tbsp flaxseed',
      '1 tbsp inositol powder (optional)',
      'Toppings: fresh berries, pumpkin seeds, cacao nibs, bee pollen',
    ],
    instructions: [
      'Blend frozen berries, banana and Greek yogurt until thick and smooth.',
      'Pour into a bowl.',
      'Top with fresh berries, pumpkin seeds, cacao nibs and bee pollen.',
      'Stir in flaxseed or inositol if using.',
    ],
    note: 'Flaxseed is key for oestrogen balance. Eat within 20 minutes of making.',
  },
  {
    id: 5,
    title: 'Spearmint & Chickpea Tabbouleh',
    subtitle: 'Anti-androgenic & anti-inflammatory',
    dieticianId: 2,
    healthLabels: ['pcos', 'anti-inflammatory', 'period'],
    prepTime: '15 min',
    cookTime: '0 min',
    servings: 3,
    gradient: 'linear-gradient(145deg, #C8E6C4 0%, #8FBC8B 60%, #5A9A56 100%)',
    emoji: '🥗',
    ingredients: [
      '1 can chickpeas, drained & rinsed',
      '1 large bunch fresh parsley, finely chopped',
      '½ cup fresh spearmint, chopped',
      '2 medium tomatoes, diced',
      '1 cucumber, diced',
      '2 tbsp olive oil',
      'Juice of 1 lemon',
      'Salt & pepper to taste',
    ],
    instructions: [
      'Rinse and drain chickpeas. Pat dry.',
      'Finely chop parsley and spearmint.',
      'Dice tomatoes and cucumber.',
      'Combine all vegetables with chickpeas in a large bowl.',
      'Dress with olive oil, lemon juice, salt and pepper.',
      'Toss well and let sit for 10 minutes before serving.',
    ],
    note: 'Spearmint has been shown to reduce androgen levels in women with PCOS.',
  },
  {
    id: 6,
    title: 'Seed Cycling Energy Balls',
    subtitle: 'Support your cycle, phase by phase',
    dieticianId: 2,
    healthLabels: ['hormones', 'pcos', 'period', 'energy'],
    prepTime: '20 min',
    cookTime: '0 min',
    servings: 12,
    gradient: 'linear-gradient(145deg, #F5E6A3 0%, #D4B800 60%, #A08800 100%)',
    emoji: '⚡',
    ingredients: [
      '½ cup pumpkin seeds',
      '½ cup flaxseeds (ground)',
      '½ cup medjool dates, pitted',
      '3 tbsp almond butter',
      '2 tbsp cacao powder',
      '1 tbsp coconut oil',
      'Pinch of sea salt',
      'Desiccated coconut to roll',
    ],
    instructions: [
      'Blend pumpkin seeds and flaxseeds in a food processor until finely ground.',
      'Add dates and blend until sticky.',
      'Add almond butter, cacao, coconut oil and salt. Blend until combined.',
      'Roll into 12 balls.',
      'Coat in desiccated coconut.',
      'Refrigerate for 30 minutes before eating.',
    ],
    note: 'These are for the follicular phase (days 1–14). Swap to sesame & sunflower seeds for the luteal phase.',
  },
  {
    id: 7,
    title: 'Fertility Boosting Lentil Soup',
    subtitle: 'Folate-rich & deeply nourishing',
    dieticianId: 3,
    healthLabels: ['fertility', 'postpartum', 'gut'],
    prepTime: '10 min',
    cookTime: '35 min',
    servings: 4,
    gradient: 'linear-gradient(145deg, #F5D5B0 0%, #D4956C 60%, #A86040 100%)',
    emoji: '🍲',
    ingredients: [
      '2 cups red lentils, rinsed',
      '1 onion, diced',
      '3 cloves garlic, minced',
      '1 tin chopped tomatoes',
      '1 tsp turmeric',
      '1 tsp cumin',
      '½ tsp cinnamon',
      '4 cups vegetable stock',
      '1 tbsp olive oil',
      'Fresh lemon juice & parsley to serve',
    ],
    instructions: [
      'Heat olive oil in a large pot. Sauté onion until soft, about 5 minutes.',
      'Add garlic and spices, cook for 1 minute until fragrant.',
      'Add lentils, chopped tomatoes and stock. Stir to combine.',
      'Bring to a boil, then simmer for 25–30 minutes until lentils are soft.',
      'Blend half the soup for a creamier texture.',
      'Finish with lemon juice and fresh parsley.',
    ],
    note: 'Red lentils are one of the best plant sources of folate, essential for early pregnancy.',
  },
  {
    id: 8,
    title: 'Golden Postpartum Recovery Broth',
    subtitle: 'Mineral-rich & restorative',
    dieticianId: 3,
    healthLabels: ['postpartum', 'energy', 'gut'],
    prepTime: '10 min',
    cookTime: '4 hr',
    servings: 6,
    gradient: 'linear-gradient(145deg, #FFF3C4 0%, #FFD700 60%, #C8A000 100%)',
    emoji: '✨',
    ingredients: [
      '1 kg chicken bones or a whole carcass',
      '2 carrots, roughly chopped',
      '2 stalks celery',
      '1 onion, halved',
      '4 cloves garlic',
      '2 tbsp apple cider vinegar',
      '1 tsp turmeric',
      '1 tsp black pepper',
      'Fresh ginger, 2 cm piece',
      'Water to cover',
    ],
    instructions: [
      'Place all ingredients in a large pot or slow cooker.',
      'Cover with cold water and add apple cider vinegar (helps extract minerals from bones).',
      'Bring to a boil, then reduce to a very low simmer.',
      'Cook for 4–8 hours, skimming any foam from the surface.',
      'Strain and discard solids.',
      'Season with salt and drink warm as a broth, or use as a soup base.',
    ],
    note: 'The apple cider vinegar is key — it draws minerals like calcium and magnesium from the bones.',
  },
  {
    id: 9,
    title: 'Prenatal Salmon & Quinoa Bowl',
    subtitle: 'Omega-3 & iron-rich',
    dieticianId: 3,
    healthLabels: ['fertility', 'hormones', 'energy'],
    prepTime: '10 min',
    cookTime: '20 min',
    servings: 2,
    gradient: 'linear-gradient(145deg, #FFD4BC 0%, #FF9B78 60%, #D46040 100%)',
    emoji: '🐟',
    ingredients: [
      '2 salmon fillets',
      '1 cup quinoa, rinsed',
      '2 cups baby spinach',
      '1 avocado, sliced',
      '½ cucumber, sliced',
      '2 tbsp sesame seeds',
      'Dressing: 2 tbsp tahini, 1 tbsp lemon juice, 1 tsp honey, water to thin',
    ],
    instructions: [
      'Cook quinoa according to packet instructions. Set aside.',
      'Season salmon with salt, pepper and a squeeze of lemon.',
      'Pan-fry salmon skin-side down for 4 minutes, flip and cook 2 more minutes.',
      'Make the tahini dressing by whisking all ingredients, adding water until pourable.',
      'Assemble bowls: quinoa base, spinach, cucumber, avocado and flaked salmon.',
      'Drizzle with tahini dressing and top with sesame seeds.',
    ],
    note: 'Salmon provides DHA which is critical for fetal brain development. Aim for 2–3 portions per week.',
  },
  {
    id: 10,
    title: 'Anti-Inflammatory Turmeric Rice Bowl',
    subtitle: 'Gentle on the gut, big on flavour',
    dieticianId: 4,
    healthLabels: ['endometriosis', 'anti-inflammatory', 'period'],
    prepTime: '10 min',
    cookTime: '25 min',
    servings: 2,
    gradient: 'linear-gradient(145deg, #FFF3B0 0%, #F5C400 60%, #C89800 100%)',
    emoji: '🍛',
    ingredients: [
      '1 cup basmati rice',
      '1 tsp turmeric',
      '½ tsp black pepper (activates curcumin)',
      '1 can chickpeas, drained',
      '2 cups baby spinach',
      '1 tbsp coconut oil',
      '½ tsp cumin seeds',
      'Fresh coriander & lime to serve',
    ],
    instructions: [
      'Cook rice with turmeric and a pinch of salt.',
      'Heat coconut oil in a pan, add cumin seeds and sizzle for 30 seconds.',
      'Add chickpeas and cook until golden and slightly crispy, about 8 minutes.',
      'Season with black pepper, salt and a pinch more turmeric.',
      'Serve rice topped with chickpeas, fresh spinach, coriander and a squeeze of lime.',
    ],
    note: 'Always pair turmeric with black pepper — it increases curcumin absorption by 2000%.',
  },
  {
    id: 11,
    title: 'Dark Chocolate Endo Energy Balls',
    subtitle: 'Magnesium-rich period pain support',
    dieticianId: 4,
    healthLabels: ['endometriosis', 'period', 'energy'],
    prepTime: '15 min',
    cookTime: '0 min',
    servings: 10,
    gradient: 'linear-gradient(145deg, #3D1A00 0%, #6B3A1F 60%, #8B5A3A 100%)',
    emoji: '🍫',
    ingredients: [
      '1 cup medjool dates, pitted',
      '3 tbsp raw cacao powder',
      '2 tbsp almond butter',
      '1 tbsp chia seeds',
      '1 tsp vanilla extract',
      'Pinch of sea salt',
      'Dark chocolate chips to roll (optional)',
    ],
    instructions: [
      'Blend dates in a food processor until a sticky paste forms.',
      'Add cacao powder, almond butter, chia seeds, vanilla and salt.',
      'Blend until combined — the mixture should be sticky and hold together.',
      'Roll into 10 small balls.',
      'Roll in dark chocolate chips if desired.',
      'Refrigerate for at least 30 minutes before eating.',
    ],
    note: 'Cacao is one of the richest food sources of magnesium, which helps relax muscles and reduce cramping.',
  },
  {
    id: 12,
    title: 'Omega-3 Chia Pudding',
    subtitle: 'Overnight, anti-inflammatory & effortless',
    dieticianId: 4,
    healthLabels: ['endometriosis', 'anti-inflammatory', 'gut'],
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 1,
    gradient: 'linear-gradient(145deg, #E8D5F0 0%, #B89FD4 60%, #8060B0 100%)',
    emoji: '💜',
    ingredients: [
      '3 tbsp chia seeds',
      '1 cup oat milk (or almond milk)',
      '1 tsp vanilla extract',
      '1 tsp maple syrup',
      'Pinch of cinnamon',
      'Toppings: blueberries, pomegranate seeds, crushed walnuts',
    ],
    instructions: [
      'Combine chia seeds, milk, vanilla, maple syrup and cinnamon in a jar.',
      'Stir well, making sure no chia seeds clump together.',
      'Stir again after 5 minutes.',
      'Seal and refrigerate overnight, or for at least 4 hours.',
      'In the morning, top with blueberries, pomegranate seeds and walnuts.',
    ],
    note: 'Blueberries and pomegranate are some of the most potent anti-inflammatory fruits available.',
  },
  {
    id: 13,
    title: 'Brazil Nut & Sea Vegetable Salad',
    subtitle: 'Selenium & iodine for thyroid support',
    dieticianId: 5,
    healthLabels: ['thyroid', 'energy', 'gut'],
    prepTime: '15 min',
    cookTime: '0 min',
    servings: 2,
    gradient: 'linear-gradient(145deg, #C4DEB8 0%, #7FB070 60%, #4A8040 100%)',
    emoji: '🥬',
    ingredients: [
      '2 cups mixed greens',
      '2 tbsp dried wakame seaweed (rehydrated)',
      '6 Brazil nuts, roughly chopped',
      '½ avocado, sliced',
      '½ cup edamame beans',
      '1 tbsp sesame seeds',
      'Dressing: 1 tbsp tamari, 1 tbsp rice vinegar, 1 tsp sesame oil, ½ tsp ginger',
    ],
    instructions: [
      'Rehydrate wakame in cold water for 5 minutes. Drain and squeeze dry.',
      'Make dressing by whisking all ingredients together.',
      'Combine greens, wakame, edamame and avocado in a bowl.',
      'Top with Brazil nuts and sesame seeds.',
      'Drizzle with dressing just before serving.',
    ],
    note: 'Just 2 Brazil nuts provide your entire daily selenium requirement, critical for converting T4 to T3.',
  },
  {
    id: 14,
    title: 'Adrenal Support Breakfast Bowl',
    subtitle: 'Cortisol-balancing & energising',
    dieticianId: 5,
    healthLabels: ['thyroid', 'energy', 'hormones'],
    prepTime: '10 min',
    cookTime: '10 min',
    servings: 1,
    gradient: 'linear-gradient(145deg, #FFF0D4 0%, #FFD090 60%, #C8A040 100%)',
    emoji: '🍳',
    ingredients: [
      '2 eggs',
      '½ cup sweet potato, roasted',
      '½ cup black beans, warmed',
      '1 cup baby spinach',
      '¼ avocado',
      '1 tbsp olive oil',
      'Salt, pepper & smoked paprika',
      'Optional: sprinkle of nutritional yeast',
    ],
    instructions: [
      'Roast diced sweet potato with olive oil and smoked paprika at 200°C for 20 minutes (can prep ahead).',
      'Fry or poach eggs to your liking.',
      'Warm black beans in a small pan.',
      'Arrange sweet potato, beans and spinach in a bowl.',
      'Top with eggs and avocado.',
      'Season well and add nutritional yeast for a B-vitamin boost.',
    ],
    note: 'Eating protein and complex carbs together first thing helps stabilise cortisol throughout the day.',
  },
  {
    id: 15,
    title: 'Hashimoto\'s Healing Bone Broth Soup',
    subtitle: 'Gut-lining repair & immune modulation',
    dieticianId: 5,
    healthLabels: ['thyroid', 'gut', 'anti-inflammatory'],
    prepTime: '10 min',
    cookTime: '30 min',
    servings: 3,
    gradient: 'linear-gradient(145deg, #B8D4E8 0%, #6090C0 60%, #305090 100%)',
    emoji: '🍜',
    ingredients: [
      '4 cups bone broth (homemade or quality store-bought)',
      '1 cup shiitake mushrooms, sliced',
      '2 cm fresh ginger, grated',
      '3 cloves garlic, minced',
      '1 cup kale, roughly torn',
      '100 g rice noodles',
      '1 tbsp tamari',
      '1 tsp miso paste',
    ],
    instructions: [
      'Bring bone broth to a gentle simmer.',
      'Add garlic, ginger and mushrooms. Simmer for 10 minutes.',
      'Cook rice noodles separately according to packet instructions.',
      'Add kale to the broth and cook for 2 minutes.',
      'Remove from heat and stir in miso paste (do not boil after adding miso).',
      'Serve broth over noodles, season with tamari.',
    ],
    note: 'Miso is a probiotic — always add it off the heat to preserve the beneficial bacteria.',
  },
]

export const getDieticianById = (id) => dieticians.find(d => d.id === id)
export const getRecipeById = (id) => recipes.find(r => r.id === id)
export const getRecipesByDietician = (dieticianId) => recipes.filter(r => r.dieticianId === dieticianId)
export const getRecipesByLabels = (labels) => {
  if (!labels || labels.length === 0) return recipes
  return recipes.filter(r => r.healthLabels.some(l => labels.includes(l)))
}
